spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @profileActive@
  boot:
    admin:
      username: ${security.user.name:admin}
      password: ${security.user.password:admin}
  redis:
    host: ${spring.redis.host:paascloud-db-redis}
    password: ${spring.redis.password:123456}
    port: ${spring.redis.port:6379}
    timeout: ${spring.redis.timeout:0}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_uac?characterEncoding=utf8&useSSL=false
    username: ${spring.datasource.username:root}
    password: ${spring.datasource.password:123456}
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin

crazyChat:
  enableSqlLogInterceptor: false
  aliyun:
    key:
      accessKeyId: yourAliyunAccessKey
      accessKeySecret: yourAliyunKeySecret
  swagger:
    title: @pom.artifactId@
    description: @pom.description@
